#!/bin/bash

# Creates the model_generation conda env, installs the pipeline's packages
# into it, verifies each one works, and writes config.sh. Re-run whenever the
# environment changes or a new pipeline stage adds packages here.
#
# Usage: bash setup_environment.sh

set -e

pipeline_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
env_name="model_generation"

conda_base="$(conda info --base 2>/dev/null)"
if [ -z "$conda_base" ] && [ -n "$CONDA_EXE" ]; then
    conda_base="$(dirname "$(dirname "$CONDA_EXE")")"
fi
if [ -z "$conda_base" ]; then
    echo "conda not found -- install Miniforge first." >&2
    exit 1
fi

conda env remove -n "$env_name" -y > /dev/null 2>&1 || true
conda create -n "$env_name" python=3.12 -y

env_bin="$conda_base/envs/$env_name/bin"

"$env_bin/pip" install carveme==1.6.6 gurobipy==13.0.2 memote==0.17.0 cobra==0.32.1 scipy
conda install -n "$env_name" -c bioconda diamond -y
conda install -n "$env_name" -c conda-forge parallel -y

# --- Verify ---
"$env_bin/python3" -c "import carveme" || { echo "carveme import failed" >&2; exit 1; }
"$env_bin/python3" -c "import cobra" || { echo "cobra import failed" >&2; exit 1; }
"$env_bin/diamond" --version > /dev/null 2>&1 || { echo "diamond not runnable" >&2; exit 1; }
"$env_bin/memote" --version > /dev/null 2>&1 || { echo "memote not runnable" >&2; exit 1; }
"$env_bin/python3" -c "
import gurobipy as gp
m = gp.Model()
m.setParam('OutputFlag', 0)
x = m.addVar()
m.setObjective(x)
m.addConstr(x >= 2.5)
m.optimize()
assert x.X == 2.5
" || { echo "gurobipy check failed -- is the Gurobi license active?" >&2; exit 1; }

# --- Write config.sh ---
config_file="$pipeline_root/scripts/config.sh"
cat > "$config_file" << EOF
#!/bin/bash
# Generated by setup_environment.sh -- do not edit by hand, re-run that
# script instead if the environment changes.

pipeline_root="$pipeline_root"

protein_sequences_dir="\$pipeline_root/data/genomes/protein_sequences"
genomic_sequences_dir="\$pipeline_root/data/genomes/genomic_sequences"
diamond_hits_dir="\$pipeline_root/data/genomes/diamond_hits"
draft_dir="\$pipeline_root/data/models/draft"
carveme_dir="\$draft_dir/carveme"
cobrapy_xml_dir="\$draft_dir/cobrapy/xml"
cobrapy_mat_dir="\$draft_dir/cobrapy/mat"

python_env="$env_bin/python3"
carve_bin="$env_bin/carve"
memote_bin="$env_bin/memote"

export PATH="$env_bin:\$PATH"
EOF
