#!/bin/bash
# Generated by setup_environment.sh -- do not edit by hand, re-run that
# script instead if the environment changes.

pipeline_root="/Users/ravichu/Desktop/UNIL/Projects/Pipeline"

protein_sequences_dir="$pipeline_root/data/genomes/protein_sequences"
genomic_sequences_dir="$pipeline_root/data/genomes/genomic_sequences"
diamond_hits_dir="$pipeline_root/data/genomes/diamond_hits"
draft_dir="$pipeline_root/data/models/draft"
carveme_dir="$draft_dir/carveme"
cobrapy_xml_dir="$draft_dir/cobrapy/xml"
cobrapy_mat_dir="$draft_dir/cobrapy/mat"

python_env="/Users/ravichu/miniforge3/envs/model_generation/bin/python3"
carve_bin="/Users/ravichu/miniforge3/envs/model_generation/bin/carve"
memote_bin="/Users/ravichu/miniforge3/envs/model_generation/bin/memote"

export PATH="/Users/ravichu/miniforge3/envs/model_generation/bin:$PATH"
